WebVendas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls')),
    path('', include('cadastros.usuarios.urls')),
    path('home/', include('home.urls')),
    path('usuarios/', include('cadastros.usuarios.urls')),
    path('colaboradores/', include('cadastros.colaboradores.urls')),
    path('vendas/', include('vendas.urls')),
    path('compras/', include('compras.urls')),
    path('clientes/', include('cadastros.clientes.urls')),
    path('fornecedores/', include('cadastros.fornecedores.urls')),
    path('produtos/', include('estoque.produtos.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadastros/clientes/urls.py
from django.urls import path
from cadastros.clientes import views


urlpatterns = [

    path('pessoa-juridica/', views.cadastro_clientes, {'pessoa_juridica': True}, name='clientes_pessoa_juridica',),
    path('cadastrar-cliente/', views.cadastrar_cliente, name='cadastrarcliente', ),
    path('buscar-cliente/', views.buscar_cliente, name='buscarcliente'),
    path('buscar-clientes/', views.buscar_clientes, name='buscarclientes'),
    path('pessoa-fisica/', views.cadastro_clientes, {'pessoa_fisica': True}, name='clientes_pessoa_fisica', ),
    path('muda-status-cliente/', views.muda_status_cliente, name='mudastatuscliente'),
]

compras/urls.py
from django.urls import path
from compras import views


urlpatterns = [
    path('', views.compras, name='compras',),
    path('registrar-nova-compra/', views.registrar_nova_compra, name='registrarnovacompra',),
    path('finalizar-compra/', views.finalizar_compra, name='finalizarcompra'),
    path('buscar-compra/', views.buscar_compra, name='buscarcompra'),
    path('buscar-compras/', views.buscar_compras, name='buscarcompras'),
    path('muda-status-compra/', views.muda_status_compra, name='mudastatuscompra'),
    path('registrar-entrada-produto/', views.registrar_entrada_produto, name='registrarentradaproduto',),
    path('cancelar-entrada-produto/', views.cancelar_entrada_produto, name='cancelarentradaproduto',),
    path('buscar-produto/', views.buscar_produto, name='buscarproduto'),
    path('financeiro-contas-a-pagar-buscar-pagamento/<int:id_compra>/', views.conta_a_pagar,),
]

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('administracao/', views.index, name='index'),
]

cadastros/clientes/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models
from cadastros.empresas.models import Empresas
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible  # esta linha somente e necessario quando usado python2.x
class Clientes(models.Model):
    nome_razao_social = models.CharField('Nome', max_length=50, blank=False)
    cpf_cnpj = models.CharField('Cpf', max_length=20, blank=False)
    rg_inscricao_estadual = models.CharField('Rg ou inscição estadual', max_length=15, blank=True)
    telefone = models.CharField('Telefone', max_length=30, blank=True)
    celular = models.CharField('Celular', max_length=30, blank=True)
    contato = models.CharField('Contato', max_length=30, blank=True)
    email = models.EmailField('E-mail', blank=False, unique=True)
    status = models.CharField('Státus', max_length=20, default='ATIVO', blank=False,)
    endereco = models.CharField('Endereço', max_length=50, blank=True)
    bairro = models.CharField('Bairro', max_length=50, blank=True)
    cidade = models.CharField('Cidade', max_length=50, blank=False)
    cep = models.CharField('CEP', max_length=10, blank=True)
    estado = models.CharField('Estado', max_length=2, blank=False)
    observacoes = models.TextField('Observações', max_length=200, blank=True)
    sexo = models.CharField('Sexo', max_length=10, blank=True)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateTimeField(auto_now=True)
    empresa = models.ForeignKey(Empresas, blank=True, null=True, on_delete=models.CASCADE)
    pessoa = models.CharField('Pessoa', blank=False, max_length=10)
    numero = models.CharField(max_length=10, blank=True)
    complemento = models.CharField(max_length=30, blank=True)
    data_nascimento_fundacao = models.DateField('Data nascimento', blank=True, null=True)
    estado_civil = models.CharField('Estado civil', max_length=15, blank=True)
    model_template = models.CharField(max_length=20, blank=True)
    sobre_nome = models.CharField('Sobre nome', max_length=50, blank=True)
    nome_fantasia = models.CharField('Nome fantasia', max_length=100, blank=True)
    inscricao_municipal = models.CharField('Rg ou inscição estadual', max_length=15, blank=True)

    def __str__(self):
        return self.nome_razao_social

    class Meta:
        db_table = 'clientes'
        ordering = ('nome_razao_social',)

cadastros/empresas/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible  # esta linha somente e necessario quando usado python2.x
class Planos(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField('Nome do plano', max_length=50, blank=False, unique=True)
    descricao = models.TextField('Descricao do plano', max_length=100, blank=True)
    valor = models.DecimalField('Valor', max_digits=15, blank=False, decimal_places=2, default='0')
    desconto_maximo = models.DecimalField('Desconto máximo %', max_digits=15, blank=False, decimal_places=2, default='0')
    observacoes = models.TextField('Observações', max_length=250, blank=True)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateField(auto_now=True)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'planos'
        ordering = ('nome',)


@python_2_unicode_compatible  # esta linha somente e necessario quando usado python2.x
class Empresas(models.Model):
    id = models.AutoField(primary_key=True)
    razao_social = models.CharField('Razão social', max_length=50, blank=True, unique=True)
    nome_fantasia = models.CharField('Nome Fantasia', max_length=50, blank=False, unique=True)
    cnpj = models.CharField('Cnpj', max_length=20, blank=True, unique=False)
    inscricao_estadual = models.CharField('Inscrição estadual', max_length=20, blank=True)
    inscricao_municipal = models.CharField('Inscrição municipal', max_length=20, blank=True)
    contato = models.CharField(max_length=30, blank=False)
    telefone = models.CharField(max_length=30, blank=False)
    celular = models.CharField(max_length=30, blank=True)
    email = models.EmailField('E-mail', blank=False)
    site = models.CharField(max_length=50, blank=False)
    cep = models.CharField(max_length=9, blank=True)
    endereco = models.CharField(max_length=40, blank=False)
    numero = models.CharField(max_length=10, blank=False)
    complemento = models.CharField(max_length=30, blank=True)
    bairro = models.CharField(max_length=50, blank=False)
    cidade = models.CharField(max_length=50, blank=False)
    uf = models.CharField(max_length=2, blank=False)
    contato_cobranca = models.CharField(max_length=30, blank=True)
    telefone_cobranca = models.CharField(max_length=30, blank=True)
    celular_cobranca = models.CharField(max_length=30, blank=True)
    email_cobranca = models.EmailField('E-mail cobrança', blank=False)
    cep_cobranca = models.CharField(max_length=9, blank=True)
    endereco_cobranca = models.CharField(max_length=40, blank=True)
    numero_cobranca = models.CharField(max_length=10, blank=True)
    complemento_cobranca = models.CharField(max_length=30, blank=True)
    bairro_cobranca = models.CharField(max_length=50, blank=True)
    cidade_cobranca = models.CharField(max_length=50, blank=True)
    uf_cobranca = models.CharField(max_length=2, blank=True)
    dia_pagamento = models.IntegerField(blank=True, null=True)
    plano = models.ForeignKey(Planos, on_delete=models.CASCADE)
    desconto = models.DecimalField('Percentual desconto %', max_digits=4, blank=False, decimal_places=2, default='0')
    forma_pagamento = models.CharField('Forma pagamento', max_length=20, blank=False, choices=(
        ('A VISTA', 'A VISTA'),
        ('PARCELADO', 'PARCELADO'),
        ('GRATUIDADE', 'GRATUIDADE'),
    ))
    meio_pagamento = models.CharField('Meio de pagamento', max_length=20, blank=False, choices=(
        ('BOLETO BANCARIO', 'BOLETO BANCARIO'),
        ('DINHEIRO EM ESPECIE', 'DINHEIRO EM ESPECIE'),
        ('DEPOSITO EM CONTA', 'DEPOSITO EM CONTA'),
        ('CARTAO DE CREDITO', 'CARTAO DE CREDITO'),
        ('CARTAO DE DEBITO', 'CARTAO DE DEBITO'),
        ('DEBITO EM CONTA', 'DEBITO EM CONTA'),
        ('GRATUIDADE', 'GRATUIDADE'),
        ('OUTROS', 'OUTROS'),
    ))
    status = models.CharField('Státus', max_length=20, blank=False, choices=(
        ('ATIVO', 'ATIVO'),
        ('INATIVO', 'INATIVO'),
        ('SUSPENSO', 'SUSPENSO'),
        ('EXCLUIDO', 'EXCLUIDO'),
        ('NEGATIVADO', 'NEGATIVADO'),
    ))
    data_inicio = models.DateField(blank=True, null=True)
    contrato = models.CharField('Contrato', max_length=30, blank=True)
    observacoes = models.TextField(max_length=250, blank=True)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome_fantasia

    class Meta:
        db_table = 'empresas'
        ordering = ('nome_fantasia',)


@python_2_unicode_compatible  # esta linha somente e necessario quando usado python2.x
class EmpresaResponsaveis(models.Model):
    id = models.AutoField(primary_key=True)
    empresa = models.ForeignKey(Empresas, on_delete=models.DO_NOTHING)
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    observacoes = models.TextField(max_length=250, blank=True)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.empresa

    class Meta:
        db_table = 'empresas_responsaveis'
        ordering = ('empresa',)

cadastros/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

compras/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from cadastros.empresas.models import Empresas
from cadastros.fornecedores.models import Fornecedores
from estoque.produtos.models import Produtos
from financeiro.contas_a_pagar.models import ContasPagar
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible  # esta linha somente e necessario quando usado python2.x
class Compras(models.Model):
    fornecedor = models.ForeignKey(Fornecedores, on_delete=models.CASCADE)
    solicitante = models.CharField(max_length=20, blank=False)
    data_compra = models.DateField()
    nota_fiscal = models.CharField(max_length=15)
    valor_total = models.DecimalField(max_digits=15, blank=False, decimal_places=2, default='0')
    pagamento = models.ForeignKey(ContasPagar, blank=True, null=True, on_delete=models.CASCADE)
    status_compra = models.CharField(max_length=30, blank=False, default='NAO LANCADO')
    observacoes = models.TextField(max_length=200, blank=True)
    empresa = models.ForeignKey(Empresas, blank=True, null=True, on_delete=models.CASCADE)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fornecedor.nome_razao_social

    class Meta:
        ordering = ('-data_compra',)
        db_table = 'compras'


@python_2_unicode_compatible  # esta linha somente e necessario quando usado python2.x
class EntradaProdutos(models.Model):
    compra = models.ForeignKey(Compras, blank=True, null=True, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produtos, blank=True, null=True, on_delete=models.CASCADE)
    quantidade = models.DecimalField(max_digits=15, blank=False, decimal_places=3)
    preco_compra = models.DecimalField(max_digits=15, blank=False, decimal_places=3, default='0')
    data_entrada = models.DateField()
    data_fabricacao = models.DateField(blank=True, null=True)
    data_validade = models.DateField(blank=True, null=True)
    numero_lote = models.CharField(max_length=20, default='0', blank=True)
    total = models.DecimalField(max_digits=15, blank=False, decimal_places=2, default='0')
    balanco = models.CharField(max_length=20, blank=False, default='ABERTO')
    status_entrada = models.CharField(max_length=15, blank=False, default='LANCADO')
    observacoes_entrada = models.TextField(max_length=200, blank=True)
    empresa = models.ForeignKey(Empresas, blank=True, null=True, on_delete=models.CASCADE)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.produto.descricao_simplificada

    class Meta:
        ordering = ('compra',)
        db_table = 'entrada_produtos'

cadastros/clientes/forms.py
from django import forms
from .models import Clientes


class FormCadastroClientes(forms.ModelForm):
    class Meta:
        model = Clientes
        fields = (
            'nome_razao_social',
            'sobre_nome',
            'rg_inscricao_estadual',
            'cpf_cnpj',
            'contato',
            'telefone',
            'celular',
            'email',
            'data_nascimento_fundacao',
            'estado_civil',
            'sexo',
            'cep',
            'endereco',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'estado',
            'status',
            'inscricao_municipal',
            'nome_fantasia',
        )

cadastros/colaboradores/forms.py
from django import forms
from .models import Colaboradores


class FormCadastroColaboradores(forms.ModelForm):
    class Meta:
        model = Colaboradores
        fields = (
            'nome',
            'sobre_nome',
            'rg',
            'cpf',
            'telefone',
            'celular',
            'email',
            'data_nascimento',
            'estado_civil',
            'sexo',
            'cep',
            'endereco',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'estado',
            'status',
        )

cadastros/fornecedores/forms.py
from django import forms
from cadastros.fornecedores.models import Fornecedores


class FormCadastroFornecedores(forms.ModelForm):
    class Meta:
        model = Fornecedores
        fields = (
            'nome_razao_social',
            'sobre_nome',
            'rg_inscricao_estadual',
            'cpf_cnpj',
            'contato',
            'telefone',
            'celular',
            'email',
            'data_nascimento_fundacao',
            'estado_civil',
            'sexo',
            'cep',
            'endereco',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'estado',
            'status',
            'inscricao_municipal',
            'nome_fantasia',
        )

compras/forms.py
from django import forms
from .models import Compras, EntradaProdutos


class FormCompras(forms.ModelForm):

    class Meta:
        model = Compras
        fields = (
            'fornecedor',
            'solicitante',
            'data_compra',
            'nota_fiscal',
            'valor_total',
            'observacoes',
        )


class FormEntradaProdutos(forms.ModelForm):

    class Meta:
        model = EntradaProdutos
        fields = (
            'compra',
            'produto',
            'quantidade',
            'preco_compra',
            'data_entrada',
            'data_fabricacao',
            'data_validade',
            'numero_lote',
            'total',
            'observacoes_entrada',
        )

cadastros/empresas/views.py
from django.shortcuts import render

# Create your views here.

cadastros/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

compras/templates/compras/forms/cadastro.html
    <form method='post' id='formPesquisa' style="margin-left:12px;">
        <div class="row">
            <div class=" form-group col-sm-3" >
                <label for="id_Pesquisa">Busca por ID</label>
                <input id='id_Pesquisa' type='number' class='form-control' name='Pesquisa' placeholder='ID compra' required>
            </div>
            <div class=" form-group col-sm-1">
                <label for="buscar">Buscar</label>
                <input id='buscar' class='btn btn-info text-left form-control' type='submit' value='Buscar' style='width:100px'>
            </div>
            </div>
    </form>
    <hr>
    <form enctype="multipart/form-data" method="post" role="form"  id="form">{% csrf_token %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                <div id="div_id" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_id">ID</label>
                    <input id="id_id" name="id_id" type="number" value="0" class="form-control" disabled>
                </div>

                <div id="div_fornecedor" class="form-group col-lg-6 col-md-6 col-sm-8 col-xs-8">
                    <label for="id_fornecedor">Nome ou razão social</label>
                    {{form_compras.fornecedor}}
                </div>

                <div id="div_solicitante" class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                    <label for="id_solicitante">Solicitante</label>
                    <input id="id_solicitante" name="solicitante" type="text" class="form-control" disabled>
                </div>

                <div id="div_data_compra" class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                    <label for="id_data_compra">Data da compra</label>
                    <input id="id_data_compra" name="data_compra" type="date" class="form-control" disabled>
                </div>

                <div id="div_nota_fiscal" class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                    <label for="id_nota_fiscal">Nota fiscal</label>
                    <input id="id_nota_fiscal" name="nota_fiscal" type="text" class="form-control" disabled>
                </div>

                <div id="div_valor_total" class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                    <label for="id_valor_total">Valor Total</label>
                    <input id="id_valor_total" name="valor_total" type="number" class="form-control" step = "any" min="0" value="0.00"  disabled>
                </div>

                <div id="div_observacoes" class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <label for="id_observacoes">Observações</label>
                    <textarea id="id_observacoes" name="observacoes" class="form-control" disabled></textarea>
                </div>

                <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <button id="btn_registrar_compra" class=" btn btn-success text-left" type="submit" disabled>Registrar</button>
                    {% if usuario.permissoes.administrador or usuario.permissoes.administrador_super or usuario.permissoes.registra_compra %}
                    <button id="btn_nova_compra" onclick="novaCompra()" type="button" class="btn btn-info">Nova</button>
                    {% endif %}
                     {% if usuario.permissoes.administrador or usuario.permissoes.administrador_super or usuario.permissoes.edita_compra %}
                    <button id="btn_alterar_compra" onclick="alterarCompra()" type="button" class="btn btn-warning" disabled>Alterar</button>
                    {% endif %}
                    <button id="btn_cancelar_operacao_compra" onclick="cancelarOperacaoCompra()" type="button" class="btn btn-danger" disabled>Cancelar</button>
                    <button id="btn_sair_compra" onclick="sairCompra()" type="button" class="btn btn-danger">Sair</button>
                </div>
            </div>
        </div>
    </form>

compras/templates/compras/forms/entrada_produtos.html
<form enctype="multipart/form-data" method="post" role="form"  id="form_entrada">{% csrf_token %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                <div id="div_id_entrada" class="form-group col-lg-2 col-md-2 col-sm-3 col-xs-3">
                    <label for="id_id_entrada">ID entrada</label>
                    <input id="id_id_entrada" name="id_id_entrada" type="number" value="0" class="form-control" disabled>
                </div>

                <div id="div_compra" class="form-group col-lg-10 col-md-10 col-sm-9 col-xs-9">
                    <label for="id_compra">Selecione uma compra</label>
                    {{form_entrada.compra}}
                </div>

                <div id="div_produto" class="form-group col-lg-5 col-md-5 col-sm-12 col-xs-12">
                    <label for="id_produto">Selecione um produto</label>
                    {{form_entrada.produto}}
                </div>

                <div id="div_quantidade" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_quantidade">Quantidade</label>
                    <input id="id_quantidade" name="quantidade" type="number" step = "any" value="0.00" min="0.001" class="form-control" style="font-size:20px;" disabled>
                </div>

                <div id="div_preco_compra" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_preco_compra">Preço unitário</label>
                    <input id="id_preco_compra" name="preco_compra" type="number" class="form-control" step = "any" min="0" value="0.00"  disabled>
                </div>

                <div id="div_total" class="form-group col-lg-3 col-md-3 col-sm-4 col-xs-4">
                    <label for="id_total">Valor total</label>
                    <input id="id_total" name="total" type="number" step = "any" min="0" value="0.00" class="form-control" disabled>
                </div>

                <div id="div_codigo_barras" class="form-group col-lg-4 col-md-4 col-sm-8 col-xs-8">
                    <label for="id_codigo_barras">Código de barras</label>
                    <input id="id_codigo_barras" name="codigo_barras" type="text" class="form-control" disabled style="font-size:20px;">
                </div>

                <div id="div_data_entrada" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_data_entrada">Data compra</label>
                    <input id="id_data_entrada" name="data_entrada" type="date" class="form-control" disabled required>
                </div>

                <div id="div_data_fabricacao" class="form-group col-lg-2 col-md-2 col-sm-6 col-xs-6">
                    <label for="id_data_fabricacao">Fabricação</label>
                    <input id="id_data_fabricacao" name="data_fabricacao" type="date" class="form-control" disabled>
                </div>

                <div id="div_data_validade" class="form-group col-lg-2 col-md-2 col-sm-6 col-xs-6">
                    <label for="id_data_validade">Validade</label>
                    <input id="id_data_validade" name="data_validade" type="date" class="form-control" disabled>
                </div>

                <div id="div_numero_lote" class="form-group col-lg-2 col-md-2 col-sm-6 col-xs-6">
                    <label for="id_numero_lote">Lote</label>
                    <input id="id_numero_lote" name="numero_lote" type="text" class="form-control" disabled>
                </div>

                <div id="div_marca" class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-6">
                    <label for="id_marca">Marca do produto</label>
                    <input id="id_marca" name="marca" type="text" class="form-control" disabled>
                </div>

                <div id="div_atualizar_preco" class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <label for="atualizar_preco">Atualizar preço de venda???</label>
                    <select id="atualizar_preco" name="atualizar_preco" class="form-control" required>
                        <option value=''></option>
                        <option value='NAO'>NÃO</option>
                        <option value='SIM'>SIM</option>
                    </select>
                </div>

                <div id="div_atualizar_preco_tabelado" class="form-group col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <label for="atualizar_preco_tabelado">Atualizar preços tabelados???</label>
                    <select id="atualizar_preco_tabelado" name="atualizar_preco_tabelado" class="form-control" required>
                        <option value=''></option>
                        <option value='NAO'>NÃO</option>
                        <option value='SIM'>SIM</option>
                    </select>
                </div>

                <div id="div_observacoes_entrada" class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <label for="id_observacoes_entrada">Observações</label>
                    <textarea id="id_observacoes_entrada" name="observacoes_entrada" disabled class="form-control"></textarea>
                </div>

                <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <button id="btn_registrar_entrada" class=" btn btn-success text-left" type="submit" disabled>Registrar</button>
                    <button id="btn_nova_entrada" type="button" class="btn btn-info" disabled>Novo</button>
                    <button id="btn_alterar_entrada" type="button" class="btn btn-warning" disabled>Alterar</button>
                    <button id="btn_cancelar_entrada" type="button" class="btn btn-danger" disabled>Cancelar</button>
                    <button id="btn_sair_entrada" type="button" class="btn btn-danger">Sair</button>
                </div>
            </div>
        </div>
    </form>

compras/templates/compras/forms/pesquisas.html
<div>

    <hr>

    <form id='formPesquisaComprasFornecedor'>
        <label style="color:silver" for="compras-fornecedor">Buscar pelo fornecedor</label>
        <input id='compras-fornecedor' required class="form-control chat-user-filter" placeholder="fornecedor" type="text">
        <button type="submit" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">Buscar</button>
    </form>

    <hr>

    <form id='formPesquisaComprasData'>
        <label style="color:silver" for="compras-data">Buscar pela data</label>
        <input id='compras-data' required class="form-control chat-user-filter" placeholder="data" type="date">
        <button type="submit" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">Buscar</button>
    </form>

    <hr>

    <form id='formPesquisaComprasNF'>
        <label style="color:silver" for="compras-nf">Buscar pela N/F</label>
        <input id='compras-nf' required class="form-control chat-user-filter" placeholder="nota fiscal" type="text">
        <button type="submit" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">Buscar</button>
    </form>

    <hr>

    <form id='formPesquisaComprasID'>
        <label style="color:silver" for="compras-id">Buscar pelo ID</label>
        <input id='compras-id' required class="form-control chat-user-filter" type="number" step = "1" min="1" placeholder="Id compra">
        <button type="submit" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">Buscar</button>
    </form>

    <hr>

</div>