WebVendas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls')),
    path('', include('cadastros.usuarios.urls')),
    path('home/', include('home.urls')),
    path('usuarios/', include('cadastros.usuarios.urls')),
    path('colaboradores/', include('cadastros.colaboradores.urls')),
    path('vendas/', include('vendas.urls')),
    path('compras/', include('compras.urls')),
    path('clientes/', include('cadastros.clientes.urls')),
    path('fornecedores/', include('cadastros.fornecedores.urls')),
    path('produtos/', include('estoque.produtos.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadastros/clientes/urls.py
from django.urls import path
from cadastros.clientes import views


urlpatterns = [

    path('pessoa-juridica/', views.cadastro_clientes, {'pessoa_juridica': True}, name='clientes_pessoa_juridica',),
    path('cadastrar-cliente/', views.cadastrar_cliente, name='cadastrarcliente', ),
    path('buscar-cliente/', views.buscar_cliente, name='buscarcliente'),
    path('buscar-clientes/', views.buscar_clientes, name='buscarclientes'),
    path('pessoa-fisica/', views.cadastro_clientes, {'pessoa_fisica': True}, name='clientes_pessoa_fisica', ),
    path('muda-status-cliente/', views.muda_status_cliente, name='mudastatuscliente'),
]

cadastros/usuarios/urls.py
from django.urls import path
from cadastros.usuarios import permissoes
from cadastros.usuarios import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('cadastrar-usuario/', views.cadastrar_usuario,
        name='cadastrarusuario', ),

    path('buscar-usuarios/', views.buscar_usuarios,
        name='buscarusuarios'),

    path('', views.cadastro_usuarios,
        name='usuarios', ),

    path('muda-status-usuario/', views.status_usuario,
        name='mudastatususuario'),

    path('cadastrar-permissao-usuario/', permissoes.cadastrar_permissao_usuario,
        name='cadastrarpermissaousuario',),

    path('buscar-permissao-usuario/', permissoes.buscar_permissao_usuario,
        name='buscarpermissaousuario'),

    path('buscar-permissoes-usuarios/', permissoes.buscar_permissoes_usuarios,
        name='buscarpermissoesusuarios'),

    path('muda-status-permissoes-usuario/', permissoes.status_permissoes_usuario,
        name='mudastatuspermissoesusuario'),

    path('muda-estilo-template/', views.muda_estilo_template, name='muda_estilo'),

    path('login/', views.LoginView.as_view(), name='login'),

    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('mudar_senha/', PasswordChangeView.as_view(
        template_name='base/alterar_senha.html',
        success_url='concluido/'
    ), name="alterarsenha"),

    path('mudar_senha/concluido/', PasswordChangeDoneView.as_view(
        template_name='base/senha_alterada_com_sucesso.html'
    )),
]

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('administracao/', views.index, name='index'),
]

cadastros/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

financeiro/contas_a_pagar/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from cadastros.empresas.models import Empresas
from cadastros.fornecedores.models import Fornecedores
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible  # esta linha somente e necessario quando usado python2.x
class ContasPagar(models.Model):
    favorecido = models.ForeignKey(Fornecedores, on_delete=models.CASCADE)
    data_conta = models.DateField(auto_now_add=True)
    valor_conta = models.DecimalField(max_digits=15, decimal_places=2)
    forma_de_pagamento = models.CharField(max_length=8, blank=False, choices=(('A VISTA', 'A VISTA'),
                                                                              ('A PRAZO', 'A PRAZO')
                                                                              ))
    meio_de_pagamento = models.CharField(max_length=15, blank=False,
                                         choices=(('DINHEIRO', 'DINHEIRO'),
                                                  ('CARTAO DEBITO', 'CARTAO DEBITO'),
                                                  ('CARTAO CREDITO', 'CARTAO CREDITO'),
                                                  ('CHEQUE', 'CHEQUE'),
                                                  ('OUTROS', 'OUTROS')
                                                  ))
    quantidade_parcelas = models.IntegerField(blank=False, default='1')
    primeiro_vencimento = models.DateField()
    valor_entrada = models.DecimalField(max_digits=15, decimal_places=2, default=0.00)
    documento_vinculado = models.IntegerField(blank=True, null=True, default=0, unique=True)
    status_conta = models.CharField(max_length=17, blank=False, default='PENDENTE', choices=(
        ('PENDENTE', 'PENDENTE'),
        ('PARCIALMENTE PAGO', 'PARCIALMENTE PAGO'),
        ('PAGO', 'PAGO'),
        ('CANCELADO', 'CANCELADO')
    ))
    descricao = models.CharField(blank=True, max_length=100)
    empresa = models.ForeignKey(Empresas, blank=True, null=True, on_delete=models.CASCADE)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateTimeField(auto_now=True)
    observacoes_conta = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ('-data_conta', 'valor_conta')
        db_table = 'contas_a_pagar'

    def __str__(self):
        data_conta = self.data_conta.strftime('%d/%m/%Y')
        valor_conta = '%0.02f' % self.valor_conta
        return '%s - %s (%s) - Compra:000%s' % (valor_conta, self.favorecido, data_conta, self.documento_vinculado)

cadastros/clientes/forms.py
from django import forms
from .models import Clientes


class FormCadastroClientes(forms.ModelForm):
    class Meta:
        model = Clientes
        fields = (
            'nome_razao_social',
            'sobre_nome',
            'rg_inscricao_estadual',
            'cpf_cnpj',
            'contato',
            'telefone',
            'celular',
            'email',
            'data_nascimento_fundacao',
            'estado_civil',
            'sexo',
            'cep',
            'endereco',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'estado',
            'status',
            'inscricao_municipal',
            'nome_fantasia',
        )

cadastros/colaboradores/forms.py
from django import forms
from .models import Colaboradores


class FormCadastroColaboradores(forms.ModelForm):
    class Meta:
        model = Colaboradores
        fields = (
            'nome',
            'sobre_nome',
            'rg',
            'cpf',
            'telefone',
            'celular',
            'email',
            'data_nascimento',
            'estado_civil',
            'sexo',
            'cep',
            'endereco',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'estado',
            'status',
        )

cadastros/clientes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from cadastros.clientes.models import Clientes
from cadastros.clientes.forms import FormCadastroClientes
import traceback
from django.http import HttpResponse, QueryDict, HttpResponseRedirect
import json
from functions.views import deserialize_form
from cadastros.usuarios.models import Usuarios
from functions.views import NORMALIZAR
from django.contrib import messages


@login_required
def cadastro_clientes(request, pessoa_fisica=None, pessoa_juridica=None):
    usuario = Usuarios.objects.get(usuario=request.user.id)
    if usuario.status != 'ATIVO' or usuario.colaborador.status != 'ATIVO' or usuario.permissoes.status != 'ATIVO' or usuario.empresa.status != 'ATIVO' or not usuario.colaborador:
        messages.add_message(request, messages.ERROR, 'Olá' + usuario.nome + '''. Desculpe-nos, mas você 
        não pode mais acessar nosso sistema...''')
        return HttpResponseRedirect('/logout/')

    template = ''
    if pessoa_fisica:
        sub_titulo = 'Cadastro de clientes pessoa física'
        template = 'clientes_pessoa_fisica'
    if pessoa_juridica:
        sub_titulo = 'Cadastro de clientes pessoa jurídica'
        template = 'clientes_pessoa_juridica'
    try:

        form_cliente = FormCadastroClientes()
    except:
        trace = traceback.format_exc()
        erro = 1
        if request.user.is_superuser:
            mensagem = 'Houve um erro interno no sistema. ' + trace
        else:
            mensagem = '''Houve um erro interno no sistema.
            Por favor, contate o suporte técnico através do E-mail: suporte@atpcsistemas.com.br.'''

    return render(request, 'clientes/'+template+'.html', locals(),)


@login_required
def cadastrar_cliente(request):
    cliente_id = request.POST.get('id')
    pessoa = request.POST.get('pessoa')
    usuario = Usuarios.objects.get(usuario=request.user.id)
    retorno = {}
    sucesso = {}
    erro = []

    if cliente_id != '0':
        cliente = Clientes.objects.get(id=int(cliente_id))

    else:
        cliente = None

    if request.method == 'POST':
        form = deserialize_form(request.POST.get('form'))
        form = FormCadastroClientes(form, instance=cliente)

        if form.is_valid():
            registro = form.save(commit=False)
            # registro.nome_razao_social = NORMALIZAR(registro.nome_razao_social)
            # registro.nome_fantasia = NORMALIZAR(registro.nome_fantasia)
            # registro.sobre_nome = NORMALIZAR(registro.sobre_nome)
            if not cliente_id != '0':
                registro.empresa = usuario.empresa
                registro.usuario = int(usuario.id)
                registro.pessoa = pessoa
                titulo_mensagem = 'SALVANDO REGISTRO . . .'
                mensagem = 'O registro foi salvo com sucesso !!!'

            else:
                titulo_mensagem = 'ALTERANDO REGISTRO . . .'
                mensagem = 'O registro foi alterado com sucesso !!!'

            registro.save()

            sucesso['success'] = True
            sucesso['mensagem'] = mensagem
            sucesso['id'] = registro.id
            sucesso['titulo'] = titulo_mensagem
            retorno = json.dumps(sucesso)

        else:

            for error in form.errors:
                erro += {error}

            titulo_mensagem = 'ERRO NA VALIDAÇÃO DOS DADOS . . .'
            mensagem = '''O formulário apresentou erros no seu preenchimento.
                       Corrija os campos listados em vermelho e tente novamente. . .'''

            retorno = json.dumps({
                'titulo': titulo_mensagem,
                'mensagem': mensagem,
                'erro': erro,
            })
    return HttpResponse(retorno, content_type="application/json")


def muda_status_cliente(request):
    # usuario = Usuarios.objects.get(usuario=request.user.id)
    sucesso = {}
    mensagem = ''
    titulo = ''
    if request.method == 'POST':
        cliente = Clientes.objects.get(pk=int(QueryDict(request.body).get('id_cliente')))
        status = QueryDict(request.body).get('status')

        cliente.status = status
        cliente.save()

        if status == 'ATIVO':
            mensagem = 'Cliente ativado com sucesso !!!'
            titulo = 'ATIVAR CADASTRO DE CLIENTE ...'

        elif status == 'INATIVO':
            mensagem = 'Cliente desativado com sucesso !!!'
            titulo = 'DESATIVAR CADASTRO DE CLIENTE ...'

        elif status == 'EXCLUIDO':
            mensagem = 'Cliente excluído com sucesso !!!'
            titulo = 'EXCLUIR CADASTRO DE CLIENTE ...'

        elif status == 'BLOQUEADO':
            mensagem = 'Cliente bloqueado com sucesso !!!'
            titulo = 'BLOQUEAR CADASTRO DE CLIENTE ...'

        elif status == 'INADIPLENTE':
            mensagem = 'Cliente posto em inadiplência com sucesso !!!'
            titulo = 'COLOCAR CLIENTE EM INADIPLENCIA ...'

        sucesso['mensagem'] = mensagem
        sucesso['titulo'] = titulo
        sucesso['status'] = status

    return HttpResponse(
            json.dumps(sucesso), content_type="application/json")


def buscar_clientes(request):
    usuario = Usuarios.objects.get(usuario=request.user.id)
    pessoa = request.GET.get('pessoa')
    tb_clientes = {}
    mensagem = ''
    clientes = []
    classe = ''
    if 'status' in request.GET and request.GET['status']:
        status = request.GET.get('status')
        if usuario.permissoes.administrador or usuario.permissoes.acessa_cadastro_cliente:
            tb_clientes = Clientes.objects.filter(empresa=usuario.empresa.id, status=status, pessoa=pessoa)
        elif usuario.permissoes.administrador_super:
            tb_clientes = Clientes.objects.filter(status=status, pessoa=pessoa)

    if 'nome' in request.GET and request.GET['nome']:
        nome = request.GET.get('nome')
        if usuario.permissoes.administrador or usuario.permissoes.acessa_cadastro_cliente:
            tb_clientes = Clientes.objects.filter(empresa=usuario.empresa.id, pessoa=pessoa, nome_razao_social__contains=nome.upper()).order_by('nome_razao_social')
        elif usuario.permissoes.administrador_super:
            tb_clientes = Clientes.objects.filter(
                nome_razao_social__contains=nome.upper(), pessoa=pessoa).order_by('nome_razao_social')

        if not tb_clientes:
            if usuario.permissoes.administrador or usuario.permissoes.acessa_cadastro_cliente:
                tb_clientes = Clientes.objects.filter(empresa=usuario.empresa.id, pessoa=pessoa, nome_razao_social__contains=nome.lower()).order_by('nome_razao_social')
            elif usuario.permissoes.administrador_super:
                tb_clientes = Clientes.objects.filter(
                    nome_razao_social__contains=nome.lower(), pessoa=pessoa).order_by('nome_razao_social')

        if not tb_clientes:
            mensagem = 'Voce pesquisou por [ ' + str(nome) + ' ] Nenhum Registro correspondeu a sua pesquisa.'
        else:
            mensagem = 'Voce pesquisou por [ ' + str(nome) + ' ] Um total de ' + str(len(tb_clientes)) + ' registros corresponderam á sua pesquisa.'

    if 'id_cliente' in request.GET and request.GET['id_cliente']:
        id_cliente = request.GET.get('id_cliente')
        if usuario.permissoes.administrador or usuario.permissoes.acessa_cadastro_cliente:
            tb_clientes = Clientes.objects.filter(empresa=usuario.empresa.id, pessoa=pessoa, pk=int(id_cliente))
        elif usuario.permissoes.administrador_super:
            tb_clientes = Clientes.objects.filter(pk=int(id_cliente), pessoa=pessoa)

    for index in tb_clientes:

        if index.status == 'ATIVO':
            classe = 'success'
        elif index.status == 'EXCLUIDO' or index.status == 'BLOQUEADO' or index.status == 'INADIPLENTE':
            classe = 'danger'
        elif index.status == 'INATIVO':
            classe = 'warning'

        clientes += [
            {
                'nome_razao_social': index.nome_razao_social,
                'sobre_nome': index.sobre_nome,
                'rg_inscricao_estadual': index.rg_inscricao_estadual,
                'cpf_cnpj': index.cpf_cnpj,
                'contato': index.contato,
                'telefone': index.telefone,
                'celular': index.celular,
                'email': index.email,
                'data_nascimento_fundacao': str(index.data_nascimento_fundacao),
                'estado_civil': index.estado_civil,
                'sexo': index.sexo,
                'cep': index.cep,
                'endereco': index.endereco,
                'numero': index.numero,
                'complemento': index.complemento,
                'bairro': index.bairro,
                'cidade': index.cidade,
                'estado': index.estado,
                'status': index.status,
                'inscricao_municipal': index.inscricao_municipal,
                'nome_fantasia': index.nome_fantasia,
                'empresa': str(index.empresa),
                'id': index.id,
                'classe': classe,
                'mensagem': mensagem,
            }
        ]
    retorno = json.dumps(clientes)
    return HttpResponse(retorno, content_type='application/json')


def buscar_cliente(request):
    cliente = {}
    id = 0
    pessoa = request.GET.get('pessoa')
    id = request.GET.get('id')
    try:
        cliente = Clientes.objects.get(pk=int(id), pessoa=pessoa)
    except:
        pass

    if cliente:
        form = FormCadastroClientes(instance=cliente)
        titulo = 'BUSCANADO REGISTROS . . .'
        mensagem = 'Busca efetuada com sucesso ! ! !'
    else:
        cliente = None
        form = FormCadastroClientes(instance=cliente)
        id = 0
        titulo = 'CLIENTE NÃO CADASTRADO . . .'
        mensagem = '''Lembre-se, um cliente pode ser cadastrado como pessoa física ou jurídica,

cadastros/empresas/views.py
from django.shortcuts import render

# Create your views here.

cadastros/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

financeiro/contas_a_pagar/views.py
from django.shortcuts import render

# Create your views here.

financeiro/contas_a_pagar/templates/contas_a_pagar/forms/cadastro.html
    <div>
<form enctype="multipart/form-data" method="post" role="form"  id="form_contas_a_pagar">{% csrf_token %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                <div id="div_id_conta" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_conta">ID</label>
                    <input id="id_conta" name="id_conta" type="number" value="0" class="form-control" disabled>
                </div>

                <div id="div_fornecedor" class="form-group col-lg-6 col-md-6 col-sm-8 col-xs-8" >
                    <label for="id_favorecido">Conta (fornecedor)</label>
                    {{form_contas_a_pagar.favorecido}}
                </div>
                <div id="div_forma_de_pagamento"  class="form-group col-lg-2 col-md-2 col-sm-6 col-xs-6">
                    <label for="id_forma_de_pagamento">Forma pagamento</label>
                    <select id="id_forma_de_pagamento" name="forma_de_pagamento" class="form-control" data-max="20" disabled>
                        <option value=""></option>
                        <option value="A VISTA">A VISTA</option>
                        <option value="A PRAZO">A PRAZO</option>
                    </select>
                </div>
                <div id="div_meio_de_pagamento"  class="form-group col-lg-2 col-md-2 col-sm-6 col-xs-6">
                    <label for="id_meio_de_pagamento">Meio pagamento</label>
                    <select id="id_meio_de_pagamento" name="meio_de_pagamento" class="form-control" data-max="20" disabled>
                        <option value=""></option>
                        <option value="DINHEIRO">DINHEIRO</option>
                        <option value="CARTAO DEBITO">CARTAO DE DÉBITO</option>
                        <option value="CARTAO CREDITO">CARTAO DE CRÉDITO</option>
                        <option value="CHEQUE">CHEQUE</option>
                        <option value="OUTROS">OUTROS</option>
                    </select>
                </div>
                <div id="div_primeiro_vencimento" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_primeiro_vencimento">1° vencimento</label>
                    <input id="id_primeiro_vencimento" name="primeiro_vencimento" type="date" class="form-control" disabled>
                </div>
                <div id="div_quantidade_parcelas" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_quantidade_parcelas">Parcelas</label>
                    <input id="id_quantidade_parcelas" name="quantidade_parcelas" type="number" step="1" value="0" min="0" class="form-control" disabled>
                </div>
                <div id="div_valor_entrada" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_valor_entrada">Entrada</label>
                    <input id="id_valor_entrada" name="valor_entrada" type="number" class="form-control" step = "any" min="0" value="0.00"  disabled>
                </div>
                <div id="div_valor_parcela" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_valor_parcela">Valor parcela</label>
                    <input id="id_valor_parcela" name="valor_parcela" type="number" class="form-control" step = "any" min="0" value="0.00"  disabled>
                </div>
                <div id="div_valor_conta" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_valor_conta">Saldo total</label>
                    <input id="id_valor_conta" name="valor_conta" type="number" class="form-control" step = "any" min="0" value="0.00"  disabled>
                </div>
                <div id="div_valor_juros" class="form-group col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <label for="id_valor_juros">Juros total</label>
                    <input id="id_valor_juros" name="valor_juros" type="number" class="form-control" step = "any" min="0" value="0.00"  disabled>
                </div>
                <div id="div_observacoes_conta" class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <label for="id_observacoes_conta">Observações</label>
                    <textarea id="id_observacoes_conta" name="observacoes_conta" class="form-control" disabled></textarea>
                </div>
                <div class="form-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <button id="btn_registrar_conta" class=" btn btn-success text-left" type="submit" disabled>Registrar</button>
                    <button id="btn_alterar_conta" type="button" class="btn btn-warning" disabled>Alterar</button>
                    <button id="btn_cancelar_conta" type="button" class="btn btn-danger" disabled>Cancelar</button>
                    <button id="btn_sair_conta" type="button" class="btn btn-danger" disabled>Sair</button>
                </div>
            </div>
        </div>
    </form>
        <br>
         <br>
         <br>
         <br>
         <br>
        <br>
        <br>
         </div>