WebVendas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls')),
    path('', include('cadastros.usuarios.urls')),
    path('home/', include('home.urls')),
    path('usuarios/', include('cadastros.usuarios.urls')),
    path('colaboradores/', include('cadastros.colaboradores.urls')),
    path('vendas/', include('vendas.urls')),
    path('compras/', include('compras.urls')),
    path('clientes/', include('cadastros.clientes.urls')),
    path('fornecedores/', include('cadastros.fornecedores.urls')),
    path('produtos/', include('estoque.produtos.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadastros/clientes/urls.py
from django.urls import path
from cadastros.clientes import views


urlpatterns = [

    path('pessoa-juridica/', views.cadastro_clientes, {'pessoa_juridica': True}, name='clientes_pessoa_juridica',),
    path('cadastrar-cliente/', views.cadastrar_cliente, name='cadastrarcliente', ),
    path('buscar-cliente/', views.buscar_cliente, name='buscarcliente'),
    path('buscar-clientes/', views.buscar_clientes, name='buscarclientes'),
    path('pessoa-fisica/', views.cadastro_clientes, {'pessoa_fisica': True}, name='clientes_pessoa_fisica', ),
    path('muda-status-cliente/', views.muda_status_cliente, name='mudastatuscliente'),
]

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('administracao/', views.index, name='index'),
]

cadastros/clientes/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models
from cadastros.empresas.models import Empresas
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible  # esta linha somente e necessario quando usado python2.x
class Clientes(models.Model):
    nome_razao_social = models.CharField('Nome', max_length=50, blank=False)
    cpf_cnpj = models.CharField('Cpf', max_length=20, blank=False)
    rg_inscricao_estadual = models.CharField('Rg ou inscição estadual', max_length=15, blank=True)
    telefone = models.CharField('Telefone', max_length=30, blank=True)
    celular = models.CharField('Celular', max_length=30, blank=True)
    contato = models.CharField('Contato', max_length=30, blank=True)
    email = models.EmailField('E-mail', blank=False, unique=True)
    status = models.CharField('Státus', max_length=20, default='ATIVO', blank=False,)
    endereco = models.CharField('Endereço', max_length=50, blank=True)
    bairro = models.CharField('Bairro', max_length=50, blank=True)
    cidade = models.CharField('Cidade', max_length=50, blank=False)
    cep = models.CharField('CEP', max_length=10, blank=True)
    estado = models.CharField('Estado', max_length=2, blank=False)
    observacoes = models.TextField('Observações', max_length=200, blank=True)
    sexo = models.CharField('Sexo', max_length=10, blank=True)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateTimeField(auto_now=True)
    empresa = models.ForeignKey(Empresas, blank=True, null=True, on_delete=models.CASCADE)
    pessoa = models.CharField('Pessoa', blank=False, max_length=10)
    numero = models.CharField(max_length=10, blank=True)
    complemento = models.CharField(max_length=30, blank=True)
    data_nascimento_fundacao = models.DateField('Data nascimento', blank=True, null=True)
    estado_civil = models.CharField('Estado civil', max_length=15, blank=True)
    model_template = models.CharField(max_length=20, blank=True)
    sobre_nome = models.CharField('Sobre nome', max_length=50, blank=True)
    nome_fantasia = models.CharField('Nome fantasia', max_length=100, blank=True)
    inscricao_municipal = models.CharField('Rg ou inscição estadual', max_length=15, blank=True)

    def __str__(self):
        return self.nome_razao_social

    class Meta:
        db_table = 'clientes'
        ordering = ('nome_razao_social',)

vendas/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from cadastros.empresas.models import Empresas
from cadastros.clientes.models import Clientes
from estoque.produtos.models import Produtos
from financeiro.contas_a_receber.models import ContasReceber
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible  # esta linha somente e necessario quando usado python2.x
class Vendas(models.Model):
    id = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(Clientes, on_delete=models.CASCADE)
    solicitante = models.CharField('Solicitante', max_length=50, blank=False)
    data_venda = models.DateField(auto_now_add=True)
    data_entrega = models.DateField()
    vencimento = models.DateField(auto_now_add=True)
    status_pedido = models.CharField('Státus do Pedido', max_length=30, blank=False, default='EM ANDAMENTO')
    valor_total = models.DecimalField('Valor total', max_digits=15, blank=False, decimal_places=2, default='0')
    desconto = models.DecimalField('Desconto', max_digits=15, blank=False, decimal_places=2, default='0')
    saldo_final = models.DecimalField('Saldo final', max_digits=15, blank=False, decimal_places=2, default='0')
    observacoes = models.TextField('Observações', max_length=200, blank=True)
    pagamento = models.ForeignKey(ContasReceber, blank=True, null=True, on_delete=models.CASCADE)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateTimeField(auto_now=True)
    empresa = models.ForeignKey(Empresas, blank=True, null=True, on_delete=models.CASCADE)
    cep = models.CharField('CEP', max_length=10, blank=True)
    endereco = models.CharField('Endereço', max_length=50, blank=True)
    numero = models.CharField(max_length=10, blank=True)
    complemento = models.CharField(max_length=30, blank=True)
    bairro = models.CharField('Bairro', max_length=50, blank=True)
    cidade = models.CharField('Cidade', max_length=50, blank=True)
    estado = models.CharField('Estado', max_length=2, blank=True)
    observacoes_entrega = models.TextField('Observações', max_length=200, blank=True)

    def __str__(self):
        return self.cliente.nome_razao_social + ' - ' + str(self.data_venda.strftime('%d/%m/%Y'))+' - Pedido: ' + \
               str(self.id)

    class Meta:
        db_table = 'vendas'
        ordering = ('-data_venda',)


@python_2_unicode_compatible  # esta linha somente e necessario quando usado python2.x
class SaidaProdutos(models.Model):
    venda = models.ForeignKey(Vendas, verbose_name="Nome/Razão social:", on_delete=models.CASCADE)
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE)
    quantidade = models.DecimalField('Quantidade', max_digits=15, blank=False, decimal_places=3)
    data_saida = models.DateField(auto_now_add=True)
    valor_unitario = models.DecimalField('Valor unitário', max_digits=15, blank=False, decimal_places=3, default='0')
    percentual_desconto = models.DecimalField('Desconto %', max_digits=15, blank=False, decimal_places=3, default='0')
    total_desconto = models.DecimalField('Desconto total', max_digits=15, blank=False, decimal_places=2, default='0')
    valor_total = models.DecimalField('Valor total', max_digits=15, blank=False, decimal_places=2, default='0')
    status = models.CharField('Státus', max_length=20, blank=False, default='AGUARDANDO',
                              choices=(
                                  ('EM SEPARACAO', 'EM SEPARACAO'),
                                  ('SEPARADO', 'SEPARADO'),
                                  ('ENTREGUE', 'ENTREGUE'),
                                  ('CANCELADO', 'CANCELADO')
                              ))
    balanco = models.CharField('Balanço', max_length=20, blank=False, default='ABERTO', choices=(
        ('ABERTO', 'ABERTO'),
        ('FECHADO', 'FECHADO')
    ))
    observacoes_saida = models.TextField('Observações', max_length=200, blank=True)
    data_registro = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateTimeField(auto_now=True)
    empresa = models.ForeignKey(Empresas, blank=True, null=True, on_delete=models.CASCADE)
    saldo_final = models.DecimalField(max_digits=15, blank=False, decimal_places=2, default='0')

    def __str__(self):
        return self.produto.descricao_simplificada

    class Meta:
        db_table = 'saida_produtos'
        ordering = ('-data_saida',)

cadastros/clientes/forms.py
from django import forms
from .models import Clientes


class FormCadastroClientes(forms.ModelForm):
    class Meta:
        model = Clientes
        fields = (
            'nome_razao_social',
            'sobre_nome',
            'rg_inscricao_estadual',
            'cpf_cnpj',
            'contato',
            'telefone',
            'celular',
            'email',
            'data_nascimento_fundacao',
            'estado_civil',
            'sexo',
            'cep',
            'endereco',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'estado',
            'status',
            'inscricao_municipal',
            'nome_fantasia',
        )

cadastros/clientes/templates/clientes/forms/cadastro_pessoa_fisica.html
<form method='post' id='formPesquisa' style="margin-left:12px;">
        <div class="row">
            <div class=" form-group col-sm-3" >
                <label for="id_Pesquisa">Busca por ID<span id="label_Pesquisa"></span></label>
                <input id='id_Pesquisa' type='number' class='form-control' name='Pesquisa' placeholder='ID fornecedor' required>
            </div>
            <div class=" form-group col-sm-1">
                <label for="buscar">Buscar<span id="label_buscar"></span></label>
                <input id='buscar' class='btn btn-info text-left form-control' type='submit' value='Buscar' style='width:100px'>
            </div>
        </div>
    </form>
    <hr>
    <form enctype="multipart/form-data" method="post" role="form"  id="form-pessoa-FISICA">{% csrf_token %}
        <div class="row">
            <div class="col-lg-12 col-md-12">

                <div id="div_id" class="form-group col-lg-2 col-md-2">
                    <label for="id_id">ID</label>
                    <input id="id_id" name="id_id" type="number" value="0" class="form-control" readonly>
                </div>

                <div id="div_nome_razao_social" class="form-group col-lg-4 col-md-4">
                    <label for="id_nome_razao_social">Nome</label>
                    <input id="id_nome_razao_social" name="nome_razao_social" type="text" class="form-control" autofocus = "autofocus" required>
                </div>

                <div id="div_sobre_nome" class="form-group col-lg-6 col-md-6">
                    <label for="id_sobre_nome">Sobre nome</label>
                    <input id="id_sobre_nome" name="sobre_nome" type="text" class="form-control" required>
                </div>

                <div id="div_rg_inscricao_estadual" class="form-group col-lg-4 col-md-4">
                    <label for="id_rg_inscricao_estadual">RG</label>
                    <input id="id_rg_inscricao_estadual" name="rg_inscricao_estadual" type="text" class="form-control">
                </div>

                <div id="div_cpf_cnpj" class="form-group col-lg-4 col-md-4">
                    <label for="id_cpf_cnpj">CPF</label>
                    <input id="id_cpf_cnpj" name="cpf_cnpj" type="text" class="form-control">
                </div>

                <div id="div_telefone" class="form-group col-lg-4 col-md-4">
                    <label for="id_telefone">Telefone</label>
                    <input id="id_telefone" name="telefone" type="text" data-mask="(99) 9999-9999" data-mask-placeholder= "X" class="form-control">
                </div>

                <div id="div_celular" class="form-group col-lg-4 col-md-4">
                    <label for="id_celular">Celular</label>
                    <input id="id_celular" name="celular" type="text" class="form-control" data-mask="(99) 9 9999-9999" data-mask-placeholder= "X">
                </div>

                <div id="div_email" class="form-group col-lg-8 col-md-8">
                    <label for="id_email">E-mail</label>
                    <input id="id_email" name="email" type="text" class="form-control">
                </div>

                <div id="div_data_nascimento_fundacao" class="form-group col-lg-3 col-md-3">
                    <label for="id_data_nascimento_fundacao">Data nascimento</label>
                    <input id="id_data_nascimento_fundacao" name="data_nascimento_fundacao" type="date" class="form-control">
                </div>

                <div id="div_sexo" class="form-group col-lg-3 col-md-3">
                    <label for="id_sexo">Sexo</label>
                    <select id="id_sexo" name="sexo" class="form-control" data-max="20" required>
                        <option value="MASCULINO">MASCULINO</option>
                        <option value="FEMININO">FEMININO</option>
                    </select>
                </div>

                <div id="div_estado_civil" class="form-group col-lg-3 col-md-3">
                    <label for="id_estado_civil">Estado civil</label>
                    <select id="id_estado_civil" name="estado_civil" class="form-control" data-max="20" required>
                        <option value="SOLTEIRO">SOLTEIRO(A)</option>
                        <option value="CASADO">CASADO(A)</option>
                        <option value="UNIAO ESTAVEL">UNIÃO ESTÁVEL</option>
                        <option value="DIVORCIADO">DIVORCIADO(A)</option>
                        <option value="SEPARADO">SEPARADO(A)</option>
                        <option value="OUTRO">OUTRO</option>
                    </select>
                </div>

                <div id="div_status" class="form-group col-lg-3 col-md-3">
                    <label for="id_status">Státus</label>
                    <select id="id_status" name="status" class="form-control" data-max="20" required>
                        <option value="ATIVO">ATIVO</option>
                        <option value="INATIVO">INATIVO</option>
                        <option value="AFASTADO">AFASTADO</option>
                        <option value="DEMITIDO">DEMITIDO</option>
                        <option value="APOSENTADO">APOSENTADO</option>
                        <option value="EXCLUIDO">EXCLUIDO</option>
                    </select>
                </div>

                <div id="div_cep" class="form-group col-lg-3 col-md-3">
                    <label for="id_cep">Cep</label>
                    <input id="id_cep" name="cep" type="text" class="form-control" data-mask="99999-999" data-mask-placeholder= "X">
                </div>

               <div id="div_endereco" class="form-group col-lg-9 col-md-9">
                    <label for="id_endereco">Endereço</label>
                    <input id="id_endereco" name="endereco" type="text" class="form-control">
                </div>

                <div id="div_numero" class="form-group col-lg-2 col-md-2">
                    <label for="id_numero">N°</label>
                    <input id="id_numero" name="numero" type="text" class="form-control">
                </div>

                <div id="div_complemento" class="form-group col-lg-4 col-md-4">
                    <label for="id_complemento">Complemento</label>
                    <input id="id_complemento" name="complemento" type="text" class="form-control">
                </div>

                <div id="div_bairro" class="form-group col-lg-6 col-md-6">
                    <label for="id_bairro">Bairro</label>
                    <input id="id_bairro" name="bairro" type="text" class="form-control">
                </div>

                <div id="div_cidade" class="form-group col-lg-10 col-md-10">
                    <label for="id_cidade">Cidade</label>
                    <input id="id_cidade" name="cidade" type="text" class="form-control" required>
                </div>

                <div id="div_estado" class="form-group col-lg-2 col-md-2">
                    <label for="id_estado">UF</label>
                    <input id="id_estado" name="estado" type="text" max="2" class="form-control" required>
                </div>

                <div id="div_observacoes" class="form-group col-lg-12 col-md-12">
                    <label for="id_observacoes">Observações</label>
                    <textarea id="id_observacoes" name="observacoes" class="form-control"></textarea>
                </div>

                <div class="form-group col-lg-12 col-md-12">
                    <input class=" btn btn-success text-left" type="submit" value="Salvar registro">
                </div>
            </div>
        </div>
    </form>

cadastros/clientes/templates/clientes/forms/cadastro_pessoa_juridica.html
<form method='post' id='formPesquisa' style="margin-left:12px;">
        <div class="row">
            <div class=" form-group col-sm-3" >
                <label for="id_Pesquisa">Busca por ID<span id="label_Pesquisa"></span></label>
                <input id='id_Pesquisa' type='number' class='form-control' name='Pesquisa' placeholder='ID colaborador' required>
            </div>
            <div class=" form-group col-sm-1">
                <label for="buscar">Buscar<span id="label_buscar"></span></label>
                <input id='buscar' class='btn btn-info text-left form-control' type='submit' value='Buscar' style='width:100px'>
            </div>
        </div>
    </form>
    <hr>
    <form enctype="multipart/form-data" method="post" role="form"  id="form-pessoa-JURIDICA">{% csrf_token %}
        <div class="row">
            <div class="col-lg-12 col-md-12">

                <div id="div_id" class="form-group col-lg-2 col-md-2">
                    <label for="id_id">ID</label>
                    <input id="id_id" name="id_id" type="number" value="0" class="form-control" readonly>
                </div>

                <div id="div_nome_razao_social" class="form-group col-lg-5 col-md-5">
                    <label for="id_nome_razao_social">Razão social</label>
                    <input id="id_nome_razao_social" name="nome_razao_social" type="text" class="form-control" autofocus = "autofocus" required>
                </div>

                <div id="div_nome_fantasia" class="form-group col-lg-5 col-md-5">
                    <label for="id_nome_fantasia">Nome fantasia</label>
                    <input id="id_nome_fantasia" name="nome_fantasia" type="text" class="form-control" required>
                </div>

                <div id="div_rg_inscricao_estadual" class="form-group col-lg-3 col-md-3">
                    <label for="id_rg_inscricao_estadual">Inscrição estadual</label>
                    <input id="id_rg_inscricao_estadual" name="rg_inscricao_estadual" type="text" class="form-control">
                </div>

                <div id="div_inscricao_municipal" class="form-group col-lg-3 col-md-3">
                    <label for="id_inscricao_municipal">Inscrição municipal</label>
                    <input id="id_inscricao_municipal" name="inscricao_municipal" type="text" class="form-control">
                </div>

                <div id="div_cpf_cnpj" class="form-group col-lg-3 col-md-3">
                    <label for="id_cpf_cnpj">CNPJ</label>
                    <input id="id_cpf_cnpj" name="cpf_cnpj" type="text" class="form-control">
                </div>

                <div id="div_data_nascimento_fundacao" class="form-group col-lg-3 col-md-3">
                    <label for="id_data_nascimento_fundacao">Data fundação</label>
                    <input id="id_data_nascimento_fundacao" name="data_nascimento_fundacao" type="date" class="form-control">
                </div>

                <div id="div_contato" class="form-group col-lg-3 col-md-3">
                    <label for="id_contato">Contato</label>
                    <input id="id_contato" name="contato" type="text" class="form-control">
                </div>

                <div id="div_telefone" class="form-group col-lg-3 col-md-3">
                    <label for="id_telefone">Telefone</label>
                    <input id="id_telefone" name="telefone" type="text" class="form-control" data-mask="(99) 9999-9999" data-mask-placeholder= "X">
                </div>

                <div id="div_celular" class="form-group col-lg-3 col-md-3">
                    <label for="id_celular">Celular</label>
                    <input id="id_celular" name="celular" type="text" class="form-control" data-mask="(99) 9 9999-9999" data-mask-placeholder= "X">
                </div>

                <div id="div_status" class="form-group col-lg-3 col-md-3">
                    <label for="id_status">Státus</label>
                    <select id="id_status" name="status" class="form-control" data-max="20" required>
                        <option value="ATIVO">ATIVO</option>
                        <option value="INATIVO">INATIVO</option>
                        <option value="BLOQUEADO">BLOQUEADO</option>
                        <option value="EXCLUIDO">EXCLUIDO</option>
                    </select>
                </div>

                <div id="div_email" class="form-group col-lg-8 col-md-8">
                    <label for="id_email">E-mail</label>
                    <input id="id_email" name="email" type="text" class="form-control">
                </div>

                <div id="div_cep" class="form-group col-lg-4 col-md-4">
                    <label for="id_cep">Cep</label>
                    <input id="id_cep" name="cep" type="text" class="form-control" data-mask="99999-999" data-mask-placeholder= "X">
                </div>

               <div id="div_endereco" class="form-group col-lg-10 col-md-10">
                    <label for="id_endereco">Endereço</label>
                    <input id="id_endereco" name="endereco" type="text" class="form-control">
                </div>

                <div id="div_numero" class="form-group col-lg-2 col-md-2">
                    <label for="id_numero">N°</label>
                    <input id="id_numero" name="numero" type="text" class="form-control">
                </div>

                <div id="div_complemento" class="form-group col-lg-3 col-md-3">
                    <label for="id_complemento">Complemento</label>
                    <input id="id_complemento" name="complemento" type="text" class="form-control">
                </div>

                <div id="div_bairro" class="form-group col-lg-5 col-md-5">
                    <label for="id_bairro">Bairro</label>
                    <input id="id_bairro" name="bairro" type="text" class="form-control">
                </div>

                <div id="div_cidade" class="form-group col-lg-4 col-md-4">
                    <label for="id_cidade">Cidade</label>
                    <input id="id_cidade" name="cidade" type="text" class="form-control" required>
                </div>

                <div id="div_estado" class="form-group col-lg-2 col-md-2">
                    <label for="id_estado">UF</label>
                    <input id="id_estado" name="estado" type="text" max="2" class="form-control" required>
                </div>

                <div id="div_observacoes" class="form-group col-lg-10 col-md-10">
                    <label for="id_observacoes">Observações</label>
                    <textarea id="id_observacoes" name="observacoes" class="form-control"></textarea>
                </div>

                <div class="form-group col-lg-12 col-md-12">
                    <input class=" btn btn-success text-left" type="submit" value="Salvar registro">
                </div>
            </div>
        </div>
    </form>

cadastros/clientes/templates/clientes/forms/pesquisas.html
<div>

    <hr>

    <form id='formPesquisaClientesNome'>
        <label style="color:silver" for="nome_colaborador">Buscar pelo nome</label>
        <input id='nome_colaborador' required class="form-control chat-user-filter" placeholder="Nome" type="text">
        <button type="submit" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">Buscar</button>
    </form>

    <hr>

    <form id='formPesquisaClientesID'>
        <label style="color:silver" for="id_cliente">Buscar pelo ID</label>
        <input id='id_cliente' required class="form-control chat-user-filter" type="number" step = "1" min="1" placeholder="Id cliente">
        <button type="submit" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">Buscar</button>
    </form>

    <hr>

</div>

cadastros/clientes/templates/clientes/forms/pesquisas_pessoa_fisica.html
<div>

    <hr>

    <form id='formPesquisaClientesNome'>
        <label style="color:silver" for="nome_cliente">Buscar pelo nome</label>
        <input id='nome_cliente' required class="form-control chat-user-filter" placeholder="Nome" type="text">
        <button type="submit" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">Buscar</button>
    </form>

    <hr>

    <form id='formPesquisaClientesID'>
        <label style="color:silver" for="id_cliente">Buscar pelo ID</label>
        <input id='id_cliente' required class="form-control chat-user-filter" type="number" step = "1" min="1" placeholder="Id cliente">
        <button type="submit" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">Buscar</button>
    </form>

    <hr>

</div>

cadastros/clientes/templates/clientes/forms/pesquisas_pessoa_juridica.html
<div>

    <hr>

    <form id='formPesquisaClientesNome'>
        <label style="color:silver" for="nome_cliente">Buscar pelo nome</label>
        <input id='nome_cliente' required class="form-control chat-user-filter" placeholder="Nome" type="text">
        <button type="submit" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">Buscar</button>
    </form>

    <hr>

    <form id='formPesquisaClientesID'>
        <label style="color:silver" for="id_cliente">Buscar pelo ID</label>
        <input id='id_cliente' required class="form-control chat-user-filter" type="number" step = "1" min="1" placeholder="Id cliente">
        <button type="submit" class="btn btn-xs btn-default btn-block sa-chat-learnmore-btn">Buscar</button>
    </form>

    <hr>

</div>